name: CI

on:
  push:

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v5

      - name: Run
        run: |
          ps -o pid,args
